name: Run commands as ubuntu 18.04
description: Runs some input command under an ubuntu 18.04 docker container

branding:
  icon: moon
  color: purple

inputs:
  command:
    description: >-
      Command to run in the container.
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
